/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PiskelReactRouteImport } from './routes/piskel-react'
import { Route as FilesRouteImport } from './routes/files'
import { Route as EditorsRouteImport } from './routes/editors'
import { Route as CodeRouteImport } from './routes/code'
import { Route as AboutRouteImport } from './routes/about'

const PiskelReactRoute = PiskelReactRouteImport.update({
  id: '/piskel-react',
  path: '/piskel-react',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorsRoute = EditorsRouteImport.update({
  id: '/editors',
  path: '/editors',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/code': typeof CodeRoute
  '/editors': typeof EditorsRoute
  '/files': typeof FilesRoute
  '/piskel-react': typeof PiskelReactRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/code': typeof CodeRoute
  '/editors': typeof EditorsRoute
  '/files': typeof FilesRoute
  '/piskel-react': typeof PiskelReactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/code': typeof CodeRoute
  '/editors': typeof EditorsRoute
  '/files': typeof FilesRoute
  '/piskel-react': typeof PiskelReactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/code' | '/editors' | '/files' | '/piskel-react'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/code' | '/editors' | '/files' | '/piskel-react'
  id: '__root__' | '/about' | '/code' | '/editors' | '/files' | '/piskel-react'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  CodeRoute: typeof CodeRoute
  EditorsRoute: typeof EditorsRoute
  FilesRoute: typeof FilesRoute
  PiskelReactRoute: typeof PiskelReactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/piskel-react': {
      id: '/piskel-react'
      path: '/piskel-react'
      fullPath: '/piskel-react'
      preLoaderRoute: typeof PiskelReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editors': {
      id: '/editors'
      path: '/editors'
      fullPath: '/editors'
      preLoaderRoute: typeof EditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  CodeRoute: CodeRoute,
  EditorsRoute: EditorsRoute,
  FilesRoute: FilesRoute,
  PiskelReactRoute: PiskelReactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
