name: Build and Deploy PWA
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install and Build 🔧
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          branch: gh-pages
          folder: dist
